name: develop-branch

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     
    # - uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     repository: podverse/podverse_api
    #     tags: stage
        
    - name: log into stage, deploy latest stage image, then run integration tests
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGE_SSH_HOST }}
        username: ${{ secrets.STAGE_SSH_USERNAME }}
        passphrase: ${{ secrets.STAGE_SSH_PASSPHRASE }}
        key: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
        command_timeout: 60m
        script: |
          exit 1
          # export NVM_DIR=~/.nvm
          # source ~/.nvm/nvm.sh
          # source ~/pgpassword.sh
          # nvm use 12.18.3
          # docker stop podverse_api_stage
          # docker rm podverse_api_stage
          # docker image rm podverse/podverse_api:stage
          # docker-compose -f /home/mitch/podverse-ops/docker-compose.stage.yml up -d podverse_api
          # sleep 120
          # cd podverse-api
          # git pull
          # npm install
          # npm run test:integration:server

    - name: Slack Notification - Success message
      if: ${{ always() }}
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
